[fbref_ids]
base_url = "https://fbref.com/en/"
league_selector_nodes = "td[data-stat='match_report'] a"


[[fbref_ids.leagues]]
league_name = "Premier-League"
league_id = 9
season_ids = [
    "1995-1996",
    "1996-1997",
    "1997-1998",
]

[[fbref_ids.leagues]]
league_name = "La-Liga"
league_id = 12
season_ids = [
    "1995-1996",
    "1996-1997",
    "1997-1998",
]

[scraping_config]
rate_limit_seconds = 1
max_retries = 3

[db_connection]
db_connection = "local"